### ISSUE TITLE
Bug: Syntax highlighting error for languages except Python

### ISSUE THREAD

**Issue by tianfudhe** [jupyter/qtconsole#116]
When I start IJulia Notebook and get the kernel `8cb2529d-d2e3-48ce-a735-cdf7b31e2841`, I want to connect to it with qtconsole:

```
jupyter qtconsole --existing 8cb2529d-d2e3-48ce-a735-cdf7b31e2841
```

Then it goes wrong that the qtconsole opened **still use syntax for Python**, not Julia, e.g., `using` is not highlighted(`using` is a keyword in Julia but not in Python).
This drives me 懵逼, I love coding in qtconsole actually...

**Comment by ccordoba12** [comment]
@minrk, I thought the pygments highlighter was changed according to the kernel spec, as it happens in the Notebook with Codemirror.

Is this not implemented in qtconsole?

**Comment by takluyver** [comment]
Looking at the code (specifically FrontendWidget and JupyterWidget) it looks like the lexer is still hard-coded to Python - we don't look at the highlighting information in kernel_info_reply.

**Comment by panlanfeng** [comment]
Will this be fixed in next release? I have the same problem when using Julia kernel.
qtconsole is a good choice for a language like Julia which does not yet have any usable IDE yet.

**Comment by minrk** [comment]
Hopefully it will be fixed in 4.3. It is mainly a question of someone finding the time to work on it.

**Comment by mrtalent** [comment]
@panlanfeng I think Atom with Ink plug-in is a temporary solution to some extent as this bug set a 4.3 milestone

**Comment by panlanfeng** [comment]
@mrtalent Thank you! I was also using ink. But I prefer qtconsole more than atom-ink because of its inline graphics feature. 
A separate figures panel (which they are trying to add) is not a good choice for exploring data analysis. That panel will have to reduce the size of either console panel or the editor panel. And the bigger problem is when I try to regenerate a previous figure I cannot find out what code I used then.

The problem with the qtconsole is it does not have an editor panel yet. (Or does it?)

**Comment by fperez** [comment]
We have very, very few cycles for the Qt console, unfortunately... So this is something where a contribution from the community is the most likely way it will get implemented.  In JupyterLab, the web console is maturing rapidly and will eventually be something we can package standalone, at that point it will let us replace the existing qt console with a component we can reuse in both web- and local modes, which is very helpful (and which, itself, reuses components from the notebook).

For this reason, our limited brainpower isn't really going to the Qt console too much.

Consider this a `raise PendingDeprecationWarning("early")` :)

**Comment by ccordoba12** [comment]
@fperez, do you mean that you're planning to shutdown qtconsole? I'd really prefer to keep it alive ;-)

I mean, I can't imagine trying to embed the web console in Spyder giving that qtconsole give us already all that we need to extend it (Qt signals and slots, shortcuts, replacing the QTextEdit widgets for ours, etc, etc).

**Comment by takluyver** [comment]
We're not shutting it down, but we want interested users like yourself to
drive it, because noone in the jupyter core team really has it as a
priority. We're happy to keep it in our infrastructure and help work out
bugs, but we're not really pushing it forwards.

**Comment by ccordoba12** [comment]
I understand, thanks for the clarification Thomas!

**Comment by fperez** [comment]
Basically think of it as "donating it to the community" :)

Our plan moving forward is to eventually wrap the web console also as a standalone GUI application, and that would become what we officially promote for what the Qt console does today.

Given we have no other Qt code nor much Qt expertise in-house, and an already vastly sprawling project otherwise, our already meager effort on the Qt console will drop to basically zero once this replacement is fully functional.  

At that point it might make more sense to consider transferring ownership of the repo to someone who can give it a better home, and Spyder could be an obvious such home.

But we can discuss that over time: for now the web console isn't package at all as a separate component, so we don't need to worry too much yet. Just a good thing for you (@ccordoba12) to be aware of for the medium term...

**Comment by ccordoba12** [comment]
@wmvanvliet, could you please take a look at this one? It's the last bug left to release 4.3 :-)

**Comment by ccordoba12** [comment]
@wmvanvliet, don't worry, I'm working on this one :-)
