### ISSUE TITLE
Exceptions not showing up when running a script with ipython magic %run

### ISSUE THREAD

**Issue by tleonhardt** [jupyter/qtconsole#140]
So if I use the IPython magic "%run" command to execute some basic code in a Python script, lets say our script contains only this code:
    1 + 'foo'

This code will should generate a TypeError Exception.  If I use %run to execute the script, then the proper exception appers in ipython at the command-line or in a Jupyter Notebook.  However, if I execute the exact same code in a Jupyter qtconsole, it doesn't show any exception.

I have tested and verified this bug using the latest version of ipython, ipykernel, jupyter_console and all of the other jupyter stuff from pip.  I have also verified it occurs on Windows, Mac, and Linux.  This also affects jupyter qtconsoles embedded in other applications like Spyder, PyCharm, or JupyterLab.

**Comment by wmvanvliet** [comment]
The messaging protocol for errors changes slightly.

see #141

**Comment by wmvanvliet** [comment]
fixed in #141

**Comment by brauliobarahona** [comment]
Hi all, is this fixed in `Jupyter QtConsole 4.2.1, Python 3.5.2` ? 

When running a script from the Jupyter QtConsole with `run -i script_name.py` the scripts seems to execute fine, but it actually stops when it reaches a line looking for a non existent variable `YE`.

When doing the same in `Jupyter console 5.0.0, Python 3.5.2 ` I get the exception `NameError: name 'YE' is not defined` as expected.

My installation is on MacOs with Anaconda 4.3.1.

**Comment by ccordoba12** [comment]
> is this fixed in Jupyter QtConsole 4.2.1, Python 3.5.2 ?

No, it was fixed in QtConsole 4.3. Please update.
