### ISSUE TITLE
No history inside Jupyter QtConsole ipdb shell

### ISSUE THREAD

**Issue by lxkain** [jupyter/qtconsole#143]
I see that there is an open issue about tab completion in ipdb, but it doesn't mention the lack of history within ipdb. The interesting thing is that this is only a problem in the qtconsole, when using jupyter-console (terminal-based), history is available.

This (and to some degree the lack of TAB-based completion) happens to be the largest inconvenience that I face when debugging using ipdb (often from within spyder), as compared to, say, WingIDE, which has a debug probe that works pretty well, but doesn't have all the goods that IPython has.

**Comment by takluyver** [comment]
I think it's accidental that debugging in jupyter_console happens to get history. That history will be shared with any `input()` prompt that comes up while running your code.

We've talked before about extending the messaging protocol with knowledge of debugging so that frontends can implement different, better debugger interfaces. But it hasn't happened.

**Comment by lxkain** [comment]
Thank you so much for explaining the situation.

**Comment by wmvanvliet** [comment]
Closing this, as this is a well known issue that first needs work at the ipython kernel side.

**Comment by brandonwillard** [comment]
Is there an open PR and/or different issue that's currently tracking the status of this functionality?
