### ISSUE TITLE
Can't pass terminal ipython options to jupyter qtconsole

### ISSUE THREAD

**Issue by skualos** [jupyter/qtconsole#172]
Before upgrading to Jupyter, I had in my file browser (Nemo) a custom command (Nemo action), so that I would right click in Nemo background, choose "Open in IPython Qt" and an IPyhton QtConsole in the folder I was browsing would open.
The command that did so was:
`ipython3 qtconsole --InteractiveShellApp.code_to_run='%cd %F'`

Since I upgrade to Jupyter, it seems that none of the [Terminal IPython options](http://ipython.readthedocs.io/en/stable/config/options/terminal.html) are read when calling
`jupyter qtconsole` or `ipython3 qtconsole`

How can I get those options (or an alternative) to work ?

**Comment by takluyver** [comment]
There isn't a good way to pass arbitrary kernel options (this doesn't work well with the abstraction that lets us use different kernels from the same frontend). But if you just need to set the working directory, you can do that before launching the frontend. For instance, if the command works with arbitrary shell syntax:

```shell
cd "%F" && jupyter qtconsole
```

If it expects a single command rather than a line of shell code, you'll need to write a little Python or shell script that changes the working directory and then launches the Qt console.

**Comment by skualos** [comment]
Hi. Thanks for the explanation.
I tried several ways to pass it a single line shell but I think it only accepts a single command.
But a shell script with:
`cd $1 && jupyter qtconsole`
and calling it with
`open_ipython_qt.sh %F`
did the trick
