### ISSUE TITLE
QtConsole blocking event loop

### ISSUE THREAD

**Issue by tecki** [jupyter/qtconsole#174]
I am integrating qtconsole (great work btw, thanks!) into a larger application. Doing so I realized that `ConsoleWidget.execute`, to be more precise in `FrontendWidget._is_complete`, contains a blocking call to `Channel.get_msg`.

This is a no-go in an event loop system. This means during that time the GUI freezes. This is mostly not seen, as the answer over the network is mostly fast. But if you have, as I do, a system where the event loop is also doing other tasks, then that's a problem.

Fortunately, I have a temporary solution: I just set `execute_on_complete_input` to `False`, which makes the code not execute, but this problem should be solved.

I'll work on a solution and present it here.

**Comment by takluyver** [comment]
A bit of the history: when the Qt console was created, it was only expected to handle Python code. Since it's written in Python, we used the `is_complete` check from IPython in the Qt console frontend code.

With Jupyter and support for multiple languages, we needed the frontend to ask the kernel whether an input is complete. We're well aware that a blocking call is bad practice in an event-loop driven application, but it usually completes quickly, and we're lazy/busy enough that we didn't want to refactor the code from a synchronous function call into something with events and callbacks.
