### ISSUE TITLE
qtconsole exits/crashes when notebook kernel is interrupted

### ISSUE THREAD

**Issue by histed** [jupyter/qtconsole#192]
Steps to reproduce:
Start a jupyter notebook on Mac OS X
run %qtconsole in a cell
Start a long calculation
Press Kernel->Interrupt
- qtconsole will close and needs to be restarted.

You can work around this by opening another console but it's a pretty poor experience esp. for new users: need to run %qtconsole again, window needs to be repositioned, etc.

Versions:
jupyter-notebook 4.2.1
anaconda                  4.1.1               np111py35_0

**Comment by takluyver** [comment]
I can reproduce it with [this notebook](https://gist.github.com/takluyver/df66c83851504ec6ccc09107ceff59e2) on Linux.

We send SIGINT to the kernel's *process group*, so that if you are running a calculation in a subprocess, that can be interrupted as well. But that also sends SIGINT to the Qt console in this case.

I suspect that the fix is for the `%qtconsole` magic to ensure that the Qt console is started in a new process group, so it doesn't get the signal.

**Comment by takluyver** [comment]
ipython/ipykernel#271 should fix it, at least for Python 3.
