### ISSUE TITLE
Qt Console hangs when editing on 4.3.0 on Ubuntu 16 

### ISSUE THREAD

**Issue by modulumath** [jupyter/qtconsole#238]
To resolve this problem:

In [1]: %edit <myfile.py>
No default editor available.
Specify a GUI text editor in the `JupyterWidget.editor` configurable to enable the %edit magic

I edited like so:

$ grep vim  ../jupyter/jupyter_qtconsole_config.py
c.JupyterWidget.editor = 'vim'

(I used full path as well w/the same results)

If I restart the console (  jupyter qtconsole & )  the Jupyter hangs forever.

I thought the editing would take place in the new graphic terminal - not try to use the shell it was launched from.

**Comment by takluyver** [comment]
> Specify a GUI text editor

It does expect a *GUI* text editor - like gvim, or atom. But you could specify a command which launches a new terminal with vim inside it. On my system, `gnome-terminal -- vim` does that.

I don't think we can 'fix' this, because I don't know of ways to:

1. Reliably tell whether the command specified is a terminal editor like `vim` or a GUI editor like `atom`.
2. Open the user's preferred terminal emulator across different platforms.

**Comment by modulumath** [comment]
Thanks for the response. Just to clarify, here's my config snippet:

## A command for invoking a system text editor. If the string contains a
#  {filename} format specifier, it will be used. Otherwise, the filename will be
#  appended to the end the command.

So I *really* thought it would edit inline of the qtconsole with whatever was mentioned. I didn't get the impression it was a gui editor.

That said, c.JupyterWidget.editor = 'gnome-terminal -- vim' works perfectly!

I am a newbie to the qtconsole so didn't really understand how it should work and would not have pursued this if I didn't like the qtconsole over the other methods ;-).

Thanks again!

**Comment by takluyver** [comment]
No problem. That help string could probably be improved to refer to a GUI text editor.

**Comment by takluyver** [comment]
#239 is my attempt at improving the help.
