### ISSUE TITLE
thread/lock mechanism appeared bugged in the console, indeed!

### ISSUE THREAD

**Issue by sylvain-bougnoux** [jupyter/qtconsole#246]
I was trying lock mechanism through the following code:
```
from threading import Thread,Lock
from time import sleep

lock=Lock()

def mythread(arg,name):
  for i in range(arg):
    with lock:
      print(name,'i  ----> ',i)
    sleep(1)

def test():
  thread1 = Thread(target = mythread, args = (5,'thread1'))
  thread1.start()
  thread2 = Thread(target = mythread, args = (5,'thread2'))
  thread2.start()
  thread1.join()
  thread2.join()

test()
```
With a possible output (completely wrong) in the console
```
thread1 i  ----> thread2  0i  ----> 
 0
thread2 thread1i  ---->   i  ----> 1 
1
thread2thread1  i  ----> i  ---->   22

thread2 thread1i  ---->   i  ----> 3 
3
thread2 i  ---->  4
thread1 i  ---->  4
```
I expected nice print separation between the 2 threads (no overlap) in the console. But instead the print statements are scrambled. In a python or ipython consoles it works properly.
Any hint on this very strange behavior?

python 3.5.3, win10, PyQt5 5.9.2, all pip uptodate.

**Comment by ccordoba12** [comment]
@takluyver, do you know what's happening here?

**Comment by CAM-Gerlach** [comment]
As a related aside, I've noticed similarly scrambled output using `joblib` and (at least) the `threading` backend; can't remember if `multiprocessing` showed the same effect.

**Comment by takluyver** [comment]
Maybe printed output goes into a thread-local buffer, which is being flushed outside the lock calls. Try using `flush=True` in your `print() call.

This is @minrk's domain - or one of them - so he can probably give a more definitive answer.

**Comment by takluyver** [comment]
Maybe printed output goes into a thread-local buffer, which is being flushed outside the lock calls. Try using `flush=True` in your `print()` call.

This is @minrk's domain - or one of them - so he can probably give a more definitive answer.

**Comment by sylvain-bougnoux** [comment]
Yes indeed it seems to work with `flush=True` (success on 5 tries)
However it is quite puzzling for beginners, I strongly vote for a fix.

**Comment by minrk** [comment]
I believe this is because print calls `stdout.write` several times: once for each piece of content and one more for the newline at the end, allowing other writes to be inserted between them. Because threaded outputs are coordinated via inproc zmq sockets, concurrent writes from two threads are *fair-queued*, essentially guaranteeing that concurrent prints from two threads will interleave writes.

I'll have to think about a better way to do ensure that writes resolve in order, which we have had to do *without* locks due to problems when the interpreter is in certain states and performance issues, but `flush` is a solid workaround right now, since flush ensures that the IO thread has consumed pending writes before returning.
