### ISSUE TITLE
qtconsole does not show TQDM (progress bar) nested loops properly

### ISSUE THREAD

**Issue by amccaugh** [jupyter/qtconsole#263]
## Description of your problem

The nested-loop function of the TQDM progress bar does not behave as it should, using version 4.3.1 of qtconsole.

When you run the TQDM progress bar module in qtconsole (in my case, running under Spyder), running a _single_ loop produces the correct ouput behavior:  the progress bar remains on a single line and updates itself.  For instance,

```
from tqdm import trange
from time import sleep

for i in trange(100, desc='Single loop'):
    sleep(0.01)
```

Produces a single line which updates itself nicely then returns you to the console

`Single loop:  50%|█████     | 50/100 [00:00<00:00, 98.52it/s]`

However, if you try to use nested loops, TQDM is no longer able to update the two lines without adding newlines, resulting in spammed whitespace.  For instance:

```
from tqdm import trange
from time import sleep

for i in trange(10, desc='1st loop'):
    for j in trange(5, desc='2nd loop', leave=False):
        for k in trange(100, desc='3nd loop'):
            sleep(0.01)
```

Will produce a console filled with extra whitespace and each new progress update will take up a newline like so:

```
1st loop:   0%|          | 0/10 [00:00<?, ?it/s]
2nd loop:   0%|          | 0/5 [00:00<?, ?it/s]

3nd loop:   0%|          | 0/100 [00:00<?, ?it/s]

3nd loop:  10%|█         | 10/100 [00:00<00:00, 97.94it/s]

3nd loop:  20%|██        | 20/100 [00:00<00:00, 96.52it/s]

3nd loop:  30%|███       | 30/100 [00:00<00:00, 96.06it/s]

3nd loop:  40%|████      | 40/100 [00:00<00:00, 96.06it/s]

3nd loop:  50%|█████     | 50/100 [00:00<00:00, 96.06it/s]

3nd loop:  60%|██████    | 60/100 [00:00<00:00, 96.21it/s]

3nd loop:  70%|███████   | 70/100 [00:00<00:00, 96.19it/s]

3nd loop:  80%|████████  | 80/100 [00:00<00:00, 96.06it/s]
```

However, in the regular IPython console started from the command line, this behaves as expected, with each line remaining in place and being updated in-place.

```
1st loop:  10%|█         | 1/10 [00:05<00:47,  5.33s/it]
2nd loop:  20%|██        | 1/5 [00:01<00:04,  1.06s/it]
3nd loop:  70%|███████   | 70/100 [00:00<00:00, 95.53it/s]
```

I have tried installing colorama as suggested in this TQDM issue [here](https://github.com/tqdm/tqdm/issues/200), but the issue remains.  From my testing, this behavior was consistent across Windows and OS X versions.  

In both OS X and Windows, the TQDM behavior works as desired if I input it directly into a command-line python console (or IPython console), but produces the spammy behavior if I run it in the Spdyer qtconsole window.

**Comment by takluyver** [comment]
I suspect that the answer is that this is out of scope. Sorry.

To explain a bit: a program sending output to a terminal can send certain special sequences of bytes to show things other than a series of lines of plain text. A terminal emulator is responsible for interpreting these sequences and drawing the state of the terminal.

The Qt console is not a terminal emulator, and doesn't really aspire to be. However, it implements a few of the simpler escape sequences for things like rewriting a single line and changing text colour. Rewriting one line is simple: carriage return `\r` goes back to the beginning of the line, and whatever is printed next overwrites it. Rewriting multiple lines is more complicated. I don't think we should try to support that - and if we ever do, I hope we use an existing terminal emulator to do this rather than implementing one ourselves.

It works if you run it in an IPython console because you're running that in a terminal emulator, which handles the escape sequences - IPython knows nothing about this. On Windows, colorama may be taking care of translating the Unix-y escape sequences into the equivalent Windows console API calls (or tqdm might be making those API calls directly - I'm not sure). Since the Qt console is not a Windows console window, those APIs aren't available.

**Comment by amccaugh** [comment]
Gotcha.  Thanks for the quick feedback.

**Comment by takluyver** [comment]
No problem. It's not 100% no - maybe someone can figure out how to make full terminal emulation compatible with rich display. But I'd expect it to be quite hard, and I don't think it's something any of us are about to try to work on.
