### ISSUE TITLE
Pressing return sometimes goes to the next line instead of running the command

### ISSUE THREAD

**Issue by impact27** [jupyter/qtconsole#372]
Example of this issue crashing a CI: https://travis-ci.org/spyder-ide/spyder/jobs/580645019

when `_trigger_is_complete_callback` is called from `eventFilter` instead of being called from `_handle_is_complete_reply`, `complete` is set to `False` even if the command is complete. 
<img width="142" alt="Screenshot 2019-09-04 at 13 05 15" src="https://user-images.githubusercontent.com/6740194/64249712-abcac900-cf14-11e9-8dc1-9c702c9281d5.png">

**Comment by wmvanvliet** [comment]
Whenever you press `Enter`, qtconsole sends the contents of the buffer to the kernel and waits for the kernel to respond back whether it considers this a complete statement or not. If the kernel is busy doing other things, qtconsole times out and instead assumes the code is incomplete. It used to be so that qtconsole will wait forever for the kernel to respond, causing everything to freeze.

**Comment by wmvanvliet** [comment]
Wait, this is not the issue you are reporting, is it?

**Comment by impact27** [comment]
The issue I am reporting is that when I press enter on a complete statement, qtconsole will sometimes treat it as an incomplete statement and insert a continuation prompt instead of executing it as it should. As my screenshot shows, this happens even when the kernel is not busy.

**Comment by impact27** [comment]
In the case where this happens (a Qevent comes before the complete reply is received) I believe it would make more sense to wait a reasonable amount of time (0.1-1s) before giving up on the complete request. The timeout now can happen after an arbitrarily short amount of time.
