### ISSUE TITLE
disable Ctrl w

### ISSUE THREAD

**Issue by quantum-booty** [jupyter/qtconsole#445]
Ctrl w closes the qt console, is it possible to remap/disable it?

**Comment by cmaureir** [comment]
Hey @quantum-booty, that shortcut comes from `QtGui.QKeySequence.Close`, since it's a standard way to define such action cross-platform:
![Screenshot_2020-10-17 QKeySequence Class Qt 4 8](https://user-images.githubusercontent.com/177982/96336877-db8a5100-1082-11eb-9356-6e820073f6fa.png)

I'd advise you not to attempt to override widely known/used shortcuts for Qt-based applications,
but if you really want to know where this is, you can look on the `qtconsole/mainwindow.py` file, where the action is defined:

```
        self.close_action=QtWidgets.QAction("&Close Tab",                                           
            self,                                                                                   
            shortcut=QtGui.QKeySequence.Close,                                                                                                                                                                       
            triggered=self.close_active_frontend                                                    
            ) 
```

**Comment by quantum-booty** [comment]
Thank you, I commented out that block of code. Now Ctrl+w is disabled.
