### ISSUE TITLE
os.get_terminal_size throws an error

### ISSUE THREAD

**Issue by peendebak** [jupyter/qtconsole#487]
When in `qtconsole` the following minimal example throws an error:
```
import os
os.get_terminal_size()
```
One would expect the method to return something like `os.terminal_size(columns=120, lines=30)`

**Comment by ccordoba12** [comment]
This needs to be patched in the kernel, not here. If you want this for Spyder only, you can submit a PR to our spyder-kernels repo:

https://github.com/spyder-ide/spyder-kernels

In particular, you need to your changes to this file:

https://github.com/spyder-ide/spyder-kernels/blob/2.x/spyder_kernels/customize/spydercustomize.py

We have a lot of patches there, so you'll get the idea of how to do one for this.

Please don't forget to make your PR against our `2.x` branch so that it's used by a future Spyder 5 version. I'm ok with merging it, so that Rich and Colorama are better supported in Spyder.

----

If you want to be more general, you can submit a PR against ipykernel, but it could take longer to be accepted or it could even be rejected because the Jupyter team is not too fond of patching standard library modules (and I sort of agree with them because the Jupyter audience is ten times larger than the Spyder one).

So it's up to you.

**Comment by ccordoba12** [comment]
I did this in PR https://github.com/spyder-ide/spyder-kernels/pull/306
