### ISSUE TITLE
QtConsole kernel restarts with "Restarting kernel..." message

### ISSUE THREAD

**Issue by eendebakpt** [jupyter/qtconsole#500]
The following minimal example results in the qtconsole restarting 
```
import numpy as np
remaining_parameters=[]

cost_function_first = lambda x: cost_function_first(np.append(x, remaining_parameters))

cost_function_first([0.])
```
with error message
```
Kernel died, restarting
```` 
The same happens within a Spyder console

The minimal example has a clear problem: an infinite recursion. But in a normal python session this results in a normal exception with clear error message, e.g.
```
...
  File "C:\develop\env-py39\lib\site-packages\numpy\core\fromnumeric.py", line 1819, in ravel
    if isinstance(a, np.matrix):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Within `qtconsole` at least a clear error message should be generated. And preferably the console not restarted.

@ccordoba12

**Comment by ccordoba12** [comment]
This is not a problem with QtConsole nor Spyder. It's an issue with IPykernel because it's the kernel in charge of running code, not the frontend (i.e. the graphical interface that sends code to it). So please report it there:

https://github.com/ipython/ipykernel

Besides that, I don't why this is happening but it could be a Windows issue since I'm not seeing it on Linux.
