### ISSUE TITLE
Tab completion inside Jupyter QtConsole ipdb shell

### ISSUE THREAD

**Issue by DevinBayly** [jupyter/qtconsole#99]
Hi there,

I have just discovered that the tab completion utility seems to be offline when using tracing with ipdb but only with qtconsole of the jupyter variety. By which I mean that the ipython qtconsole still has functioning tab completion during an ipdb trace so I am curious if anyone knows how to enable this, or if this needs to become something to eventually work into a later version.

Cheers,
Devin

**Comment by takluyver** [comment]
I think you're mistaken about ipython qtconsole. The Qt console has never had tab completion inside the debugger, and there's no easy way to do it. See ipython/ipython#902.

**Comment by DevinBayly** [comment]
ok, I'll transfer my comment to the jupyter console issue page then?

**Comment by takluyver** [comment]
I'm not quite sure what you mean.

This is an issue for all Jupyter frontends, because our messaging protocol does not know about debugging specifically. The Python debugger is just calling `input()` to prompt the user for the next command, and that gets passed on to the frontends as a generic 'prompt for a line of input' message. There's no completion machinery associated with that.

We have vaguely talked about adding some specialised debugging messages to the protocol, which would allow building a nicer debugger interface in Jupyter frontends. But it would be quite a lot of work, and it's not very high priority.

**Comment by wmvanvliet** [comment]
Closing this, as it is a well known issue that first needs to be addressed in the ipython kernel itself.
